version: 0.2

phases:
  install:
    commands:
      - echo "Installing Packer..."
      - curl -L -o packer.zip https://releases.hashicorp.com/packer/1.7.8/packer_1.7.8_linux_amd64.zip
      - unzip packer.zip
      - chmod +x packer
      - mv packer /usr/local/bin/
  pre_build:
    commands:
      - "echo 'Fetching the latest base AMI from Parameter Store...'"
      - "BASE_AMI=$(aws ssm get-parameter --name '/RIDA/BaseAMI' --query 'Parameter.Value' --output text)"
      - echo "Base AMI: $BASE_AMI"
      - echo "Updating packer template with base AMI..."
      - sed -i "s/REPLACE_BASE_AMI_ID/$BASE_AMI/" packer-template.json
  build:
    commands:
      - echo "Building the new application AMI..."
      - "packer build packer-template.json | tee packer_output.log"
      - "NEW_AMI=$(grep 'AMI: ' packer_output.log | awk '{print $NF}' | tail -n1)"
      - echo "New AMI created: $NEW_AMI"
  post_build:
    commands:
      - echo "Storing new AMI ID in Parameter Store..."
      - aws ssm put-parameter --name "/RIDA/AppAMI" --value "$NEW_AMI" --type String --overwrite --region us-east-1
artifacts:
  files:
    - packer_output.log
